[package]
name = "discord-data-package-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
csv = "1.1.6"
regex = "1.6.0"